version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: host
volumes:
  mysql_data:
